import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
//import "@/styles/globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });



export const metadata: Metadata = {
  title: "MatchMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      
        <Providers>
         
          {children}
        </Providers>
  
      </body>
    </html>
  );
}
